spring:
  application:
    name: CentNeoSupportDeskAuthSvc
  profiles:
    active: prod
  mvc:
    servlet:
      path: /api

  redis:
    host: localhost
    port: 6379

  management:
    endpoints:
      web:
        exposure:
          include: health, info, mappings
    endpoint:
      health:
        show-details: always

  #  ldap:
  #    urls: ldap://ldap.forumsys.com:389
  #    base: dc=example,dc=com
  #    username: cn=read-only-admin,dc=example,dc=com
  #    password: password
  #    user-dn-patterns: uid={0},dc=example,dc=com

  ldap:
    urls: "ldap://10.1.36.160:389"
    base: "dc=cbi,dc=co,dc=in"
    username: "CN=ks_nsd01,OU=APPSUSER,DC=CBI,DC=CO,DC=IN"
    password: "Master99@"
    #anonymous-read-only : false

  #  security:
  #    ldap:
  #      user-search-base:  "OU=APPSUSER"
  #      user-search-filter: "(sAMAccountName={0})"
  #      group-search-base: "CN=ks_nsd01,OU=APPSUSER,DC=CBI,DC=CO,DC=IN"
  #      group-search-filter: "member={0}"

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 9002

jwt:
  alg: RS256
  private-key-file: classpath:keys/jwt_private_key_pkcs8.pem
  public-key-file: classpath:keys/jwt_public_key.pem
  issuer: centneo
  access-ttl-ms: 18000000
  refresh-ttl-ms: 86400000

logging:
  level:
    org.springframework: INFO
    com.centNeo: DEBUG
    org.springframework.security: DEBUG
    org.springframework.ldap: TRACE
    org.springframework.security.ldap: TRACE
#    com.zaxxer.hikari: TRACE
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE
#    org.hibernate.orm.connections.pooling: DEBUG
